services:
  postgres_db:
    image: postgres:${POSTGRES_SERVER_VERSION}
    container_name: postgres_db
    shm_size: 128mb
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_EXPOSE_PORT}:${POSTGRES_SERVER_PORT}
    networks:
      - app-network
    
  keycloak:
    image: bitnami/keycloak:${KEYCLOAK_SERVER_VERSION}
    container_name: keycloak
    env_file: .env
    environment:
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_DATABASE_VENDOR=${KEYCLOAK_DB_VENDOR}
      - KEYCLOAK_DATABASE_HOST=${KEYCLOAK_DB_HOST}
      - KEYCLOAK_DATABASE_PORT=${KEYCLOAK_DB_PORT}
      - KEYCLOAK_DATABASE_NAME=${KEYCLOAK_DB_DATABSE}
      - KEYCLOAK_DATABASE_USER=${KEYCLOAK_DB_USER}
      - KEYCLOAK_DATABASE_PASSWORD=${KEYCLOAK_DB_PASS}
      - KEYCLOAK_DB_URL=jdbc:${KEYCLOAK_DB_VENDOR}://localhost:${KEYCLOAK_DB_PORT}/${KEYCLOAK_DB_DATABASE}
    ports:
      - ${KEYCLOAK_EXPOSE_PORT}:${KEYCLOAK_SERVER_PORT}
    depends_on:
      - postgres_db
    networks: 
      - app-network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL:${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD:${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - postgres_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge